import { z } from "zod";

const gameSchema = z.object({
  search: z.string(),
  limit: z.number(),
  page: z.number(),
  fields: z.object({
    age_ratings: z.boolean().optional(),
    aggregated_rating: z.boolean().optional(),
    aggregated_rating_count: z.boolean().optional(),
    alternative_names: z.boolean().optional(),
    artworks: z.boolean().optional(),
    bundles: z.boolean().optional(),
    category: z.boolean().optional(),
    checksum: z.boolean().optional(),
    collection: z.boolean().optional(),
    collections: z.boolean().optional(),
    cover: z.boolean().optional(),
    created_at: z.boolean().optional(),
    dlcs: z.boolean().optional(),
    expanded_games: z.boolean().optional(),
    expansions: z.boolean().optional(),
    external_games: z.boolean().optional(),
    first_release_date: z.boolean().optional(),
    follows: z.boolean().optional(),
    forks: z.boolean().optional(),
    franchise: z.boolean().optional(),
    franchises: z.boolean().optional(),
    game_engines: z.boolean().optional(),
    game_localizations: z.boolean().optional(),
    game_modes: z.boolean().optional(),
    genres: z.boolean().optional(),
    hypes: z.boolean().optional(),
    involved_companies: z.boolean().optional(),
    keywords: z.boolean().optional(),
    language_supports: z.boolean().optional(),
    multiplayer_modes: z.boolean().optional(),
    name: z.boolean().optional(),
    parent_game: z.boolean().optional(),
    platforms: z.boolean().optional(),
    player_perspectives: z.boolean().optional(),
    ports: z.boolean().optional(),
    rating: z.boolean().optional(),
    rating_count: z.boolean().optional(),
    release_dates: z.boolean().optional(),
    remakes: z.boolean().optional(),
    remasters: z.boolean().optional(),
    screenshots: z.boolean().optional(),
    similar_games: z.boolean().optional(),
    slug: z.boolean().optional(),
    standalone_expansions: z.boolean().optional(),
    status: z.boolean().optional(),
    storyline: z.boolean().optional(),
    summary: z.boolean().optional(),
    tags: z.boolean().optional(),
    themes: z.boolean().optional(),
    total_rating: z.boolean().optional(),
    total_rating_count: z.boolean().optional(),
    updated_at: z.boolean().optional(),
    url: z.boolean().optional(),
    version_parent: z.boolean().optional(),
    version_title: z.boolean().optional(),
    videos: z.boolean().optional(),
    websites: z.boolean().optional(),
  }),
});

export default gameSchema;
